# 베이스 이미지 설정
FROM python:3.10-slim

# 작업 디렉토리 설정
WORKDIR /app

# 필요 패키지 사전 설치
RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    libglib2.0-0

# 프로젝트의 requirements.txt 파일을 작업 디렉토리로 복사
COPY requirements.txt .

# 모델 파일 복사
COPY vectormodel /opt/lh/vectormodel

# requirements.txt 파일에 명시된 Python 패키지들을 설치
RUN pip install --no-cache-dir -r requirements.txt

# 프로젝트의 모든 파일을 작업 디렉토리로 복사
COPY . .

# FastAPI 애플리케이션을 uvicorn으로 실행
CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
